### PR TITLE
Added Input Mapping Tool tutorial

### PR DESCRIPTION
**Pull request by Michael10055**
Only took 6 months.

### CODE REVIEW

**Comment by only-a-ptr** [comment]
Wow, nice work on the mapping tool, I only found out now... just push the sources to GitHub somewhere, else you're in violation of GPL 😆

**Comment by Michael10055** [comment]
Well, I'd have to do some major cleanup first - It's based on 0.37.126's RoRConfig, didn't change project names or anything, just started to remove code and hoped it still compiled. lol
But yeah, I'll get it on GitHub eventually.

**Comment by only-a-ptr** [comment]
@Michael10055 I know what you mean, this version shared code between RoR and RoRConfig. Don't bother cleaning it up, just add README saying "bloody mess ahead" + what you just wrote. The point is for me to have something functional to help me wrap up https://github.com/RigsOfRods/rigs-of-rods/issues/1070 or finally add input config to RoR's ingame settings.

**Comment by Michael10055** [comment]
Welp, it's uploaded: https://github.com/Michael10055/RoRInputMappingTool

**Pull request merged**
